/* Parser4MIBTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. Parser4MIBTokenManager.java */
package com.hellonms.platforms.emp_orange.share.parser.snmp;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/** Token Manager. */
@SuppressWarnings("unused")public class Parser4MIBTokenManager implements Parser4MIBConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0xc57cbf70000L) != 0L)
         {
            jjmatchedKind = 47;
            return 66;
         }
         if ((active0 & 0x10800000000L) != 0L)
         {
            jjmatchedKind = 47;
            return 15;
         }
         if ((active0 & 0x34000000L) != 0L)
         {
            jjmatchedKind = 47;
            return 45;
         }
         return -1;
      case 1:
         if ((active0 & 0x34000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 1;
            return 44;
         }
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 1;
            return 14;
         }
         if ((active0 & 0xc5fcbf70000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 1;
            return 66;
         }
         return -1;
      case 2:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 2;
            return 13;
         }
         if ((active0 & 0x40000L) != 0L)
            return 66;
         if ((active0 & 0xc5fcbf30000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 2;
            return 66;
         }
         if ((active0 & 0x34000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 2;
            return 43;
         }
         return -1;
      case 3:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 3;
            return 12;
         }
         if ((active0 & 0x34000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 3;
            return 42;
         }
         if ((active0 & 0x80000400000L) != 0L)
            return 66;
         if ((active0 & 0x45fcbb30000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 3;
            return 66;
         }
         return -1;
      case 4:
         if ((active0 & 0x45fc2b10000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 4;
            return 66;
         }
         if ((active0 & 0x8000000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 47;
               jjmatchedPos = 3;
            }
            return 67;
         }
         if ((active0 & 0x1020000L) != 0L)
            return 66;
         if ((active0 & 0x34000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 4;
            return 30;
         }
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 4;
            return 11;
         }
         return -1;
      case 5:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 5;
            return 10;
         }
         if ((active0 & 0x200000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 47;
               jjmatchedPos = 4;
            }
            return 67;
         }
         if ((active0 & 0x34000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 5;
            return 68;
         }
         if ((active0 & 0x4800000000L) != 0L)
            return 66;
         if ((active0 & 0x415cab10000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 5;
            return 66;
         }
         return -1;
      case 6:
         if ((active0 & 0x41000300000L) != 0L)
            return 66;
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 6;
            return 6;
         }
         if ((active0 & 0x64a810000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 6;
            return 66;
         }
         if ((active0 & 0x1b4000000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 47;
               jjmatchedPos = 5;
            }
            return 67;
         }
         return -1;
      case 7:
         if ((active0 & 0x10000000000L) != 0L)
            return 69;
         if ((active0 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 47;
               jjmatchedPos = 6;
            }
            return 67;
         }
         if ((active0 & 0x7fc010000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 7;
            return 66;
         }
         if ((active0 & 0x800000L) != 0L)
            return 66;
         return -1;
      case 8:
         if ((active0 & 0x7f6010000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 8;
            return 66;
         }
         if ((active0 & 0x8000000L) != 0L)
            return 66;
         return -1;
      case 9:
         if ((active0 & 0x7f6010000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 9;
            return 66;
         }
         return -1;
      case 10:
         if ((active0 & 0x4010000L) != 0L)
            return 66;
         if ((active0 & 0x7f2000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 10;
            return 66;
         }
         return -1;
      case 11:
         if ((active0 & 0x20000000L) != 0L)
            return 66;
         if ((active0 & 0x7d2000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 11;
            return 66;
         }
         return -1;
      case 12:
         if ((active0 & 0x392000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 12;
            return 66;
         }
         if ((active0 & 0x440000000L) != 0L)
         {
            if (jjmatchedPos < 11)
            {
               jjmatchedKind = 47;
               jjmatchedPos = 11;
            }
            return 67;
         }
         return -1;
      case 13:
         if ((active0 & 0x7d2000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 13;
            return 66;
         }
         return -1;
      case 14:
         if ((active0 & 0x90000000L) != 0L)
            return 66;
         if ((active0 & 0x742000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 14;
            return 66;
         }
         return -1;
      case 15:
         if ((active0 & 0x742000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 15;
            return 66;
         }
         return -1;
      case 16:
         if ((active0 & 0x242000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 16;
            return 66;
         }
         if ((active0 & 0x500000000L) != 0L)
            return 66;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 8);
      case 41:
         return jjStopAtPos(0, 9);
      case 44:
         return jjStopAtPos(0, 13);
      case 46:
         return jjStopAtPos(0, 12);
      case 58:
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 59:
         return jjStopAtPos(0, 15);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x200000000L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x80000020000L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x240000L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x41000900000L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x181000000L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x440000000L);
      case 79:
         return jjMoveStringLiteralDfa1_0(0x34000000L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x10800000000L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0xa000000L);
      case 91:
         return jjStopAtPos(0, 10);
      case 93:
         return jjStopAtPos(0, 11);
      case 123:
         return jjStopAtPos(0, 6);
      case 124:
         return jjStopAtPos(0, 14);
      case 125:
         return jjStopAtPos(0, 7);
      default :
         return jjMoveNfa_0(5, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 58:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000L);
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L);
      case 66:
         return jjMoveStringLiteralDfa2_0(active0, 0x34000000L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x10002030000L);
      case 71:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000L);
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000L);
      case 77:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000900000L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000040000L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x5c0000000L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x8400000L);
      case 88:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000L);
      case 89:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 61:
         if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(2, 19);
         break;
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
      case 67:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000L);
      case 68:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(2, 18, 66);
         return jjMoveStringLiteralDfa3_0(active0, 0x180000000L);
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000L);
      case 70:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L);
      case 71:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000L);
      case 74:
         return jjMoveStringLiteralDfa3_0(active0, 0x34000000L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000400000L);
      case 80:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000b00000L);
      case 81:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L);
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0xc0440000000L);
      case 88:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa4_0(active0, 0x40034000000L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x4440030000L);
      case 76:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000800000L);
      case 77:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 22, 66);
         break;
      case 78:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000L);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0x300000L);
      case 80:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000L);
      case 83:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 43, 66);
         break;
      case 84:
         return jjMoveStringLiteralDfa4_0(active0, 0x802000000L);
      case 85:
         return jjMoveStringLiteralDfa4_0(active0, 0x10180000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000L);
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000L);
      case 67:
         return jjMoveStringLiteralDfa5_0(active0, 0x4034000000L);
      case 69:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L);
      case 70:
         return jjMoveStringLiteralDfa5_0(active0, 0x440000000L);
      case 71:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000L);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000800000L);
      case 76:
         return jjMoveStringLiteralDfa5_0(active0, 0x180000000L);
      case 78:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(4, 17, 66);
         return jjMoveStringLiteralDfa5_0(active0, 0x10000L);
      case 79:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(4, 24, 66);
         break;
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0x300000L);
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000L);
      case 85:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000L);
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000L);
      case 67:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L);
      case 69:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 38, 66);
         return jjMoveStringLiteralDfa6_0(active0, 0x41180000000L);
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0x440010000L);
      case 78:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000000L);
      case 84:
         return jjMoveStringLiteralDfa6_0(active0, 0x3c300000L);
      case 88:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(5, 35, 66);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa7_0(active0, 0x1b4000000L);
      case 67:
         return jjMoveStringLiteralDfa7_0(active0, 0x10640000000L);
      case 68:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 36, 66);
         break;
      case 73:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000L);
      case 76:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L);
      case 82:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 42, 66);
         break;
      case 83:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 20, 66);
         else if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(6, 21, 66);
         break;
      case 84:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000L);
      case 89:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000L);
      case 65:
         return jjMoveStringLiteralDfa8_0(active0, 0x640000000L);
      case 67:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000000L);
      case 69:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 40, 69);
         break;
      case 71:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000L);
      case 73:
         return jjMoveStringLiteralDfa8_0(active0, 0x90010000L);
      case 80:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000L);
      case 84:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(7, 23, 66);
         return jjMoveStringLiteralDfa8_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000L);
      case 68:
         return jjMoveStringLiteralDfa9_0(active0, 0x90000000L);
      case 69:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(8, 27, 66);
         break;
      case 79:
         return jjMoveStringLiteralDfa9_0(active0, 0x100010000L);
      case 80:
         return jjMoveStringLiteralDfa9_0(active0, 0x200000000L);
      case 82:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000000L);
      case 84:
         return jjMoveStringLiteralDfa9_0(active0, 0x440000000L);
      case 89:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa10_0(active0, 0x200000000L);
      case 69:
         return jjMoveStringLiteralDfa10_0(active0, 0x90000000L);
      case 73:
         return jjMoveStringLiteralDfa10_0(active0, 0x440000000L);
      case 77:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000000L);
      case 78:
         return jjMoveStringLiteralDfa10_0(active0, 0x10000L);
      case 79:
         return jjMoveStringLiteralDfa10_0(active0, 0x22000000L);
      case 80:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 66:
         return jjMoveStringLiteralDfa11_0(active0, 0x200000000L);
      case 69:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(10, 26, 66);
         break;
      case 78:
         return jjMoveStringLiteralDfa11_0(active0, 0x92000000L);
      case 79:
         return jjMoveStringLiteralDfa11_0(active0, 0x440000000L);
      case 80:
         return jjMoveStringLiteralDfa11_0(active0, 0x100000000L);
      case 83:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(10, 16, 66);
         break;
      case 85:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa12_0(active0, 0x200000000L);
      case 76:
         return jjMoveStringLiteralDfa12_0(active0, 0x100000000L);
      case 78:
         return jjMoveStringLiteralDfa12_0(active0, 0x440000000L);
      case 80:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(11, 29, 66);
         break;
      case 84:
         return jjMoveStringLiteralDfa12_0(active0, 0x90000000L);
      case 86:
         return jjMoveStringLiteralDfa12_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa13_0(active0, 0x440000000L);
      case 69:
         return jjMoveStringLiteralDfa13_0(active0, 0x2000000L);
      case 73:
         return jjMoveStringLiteralDfa13_0(active0, 0x190000000L);
      case 76:
         return jjMoveStringLiteralDfa13_0(active0, 0x200000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa14_0(active0, 0x100000000L);
      case 71:
         return jjMoveStringLiteralDfa14_0(active0, 0x40000000L);
      case 73:
         return jjMoveStringLiteralDfa14_0(active0, 0x200000000L);
      case 78:
         return jjMoveStringLiteralDfa14_0(active0, 0x2000000L);
      case 84:
         return jjMoveStringLiteralDfa14_0(active0, 0x490000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 78:
         return jjMoveStringLiteralDfa15_0(active0, 0x100000000L);
      case 82:
         return jjMoveStringLiteralDfa15_0(active0, 0x40000000L);
      case 84:
         return jjMoveStringLiteralDfa15_0(active0, 0x202000000L);
      case 89:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(14, 28, 66);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(14, 31, 66);
         return jjMoveStringLiteralDfa15_0(active0, 0x400000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa16_0(active0, 0x100000000L);
      case 73:
         return jjMoveStringLiteralDfa16_0(active0, 0x202000000L);
      case 79:
         return jjMoveStringLiteralDfa16_0(active0, 0x40000000L);
      case 80:
         return jjMoveStringLiteralDfa16_0(active0, 0x400000000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(16, 32, 66);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(16, 34, 66);
         return jjMoveStringLiteralDfa17_0(active0, 0x200000000L);
      case 79:
         return jjMoveStringLiteralDfa17_0(active0, 0x2000000L);
      case 85:
         return jjMoveStringLiteralDfa17_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
private int jjMoveStringLiteralDfa17_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0);
      return 17;
   }
   switch(curChar)
   {
      case 78:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(17, 25, 66);
         break;
      case 80:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(17, 30, 66);
         break;
      case 83:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(17, 33, 66);
         break;
      default :
         break;
   }
   return jjStartNfa_0(16, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 66;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 30:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 5:
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 44)
                        kind = 44;
                     { jjCheckNAdd(20); }
                  }
                  else if (curChar == 39)
                     { jjCheckNAddStates(0, 5); }
                  else if (curChar == 34)
                     { jjCheckNAddTwoStates(27, 28); }
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 19;
                  else if (curChar == 48)
                  {
                     if (kind > 44)
                        kind = 44;
                  }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 12:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 43:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if ((0x100002600L & l) != 0L)
                     { jjCheckNAddTwoStates(7, 9); }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 67:
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  { jjCheckNAddTwoStates(24, 25); }
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if ((0x100002600L & l) != 0L)
                     { jjCheckNAddTwoStates(31, 41); }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAdd(25); }
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 0:
                  if (curChar != 45)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjCheckNAddStates(6, 8); }
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjCheckNAddStates(6, 8); }
                  break;
               case 2:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 3:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 4:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 7:
                  if ((0x100002600L & l) != 0L)
                     { jjCheckNAddTwoStates(7, 9); }
                  break;
               case 17:
                  if (curChar == 48 && kind > 44)
                     kind = 44;
                  break;
               case 18:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 19:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  { jjCheckNAdd(20); }
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  { jjCheckNAdd(20); }
                  break;
               case 22:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 24:
                  if (curChar == 45)
                     { jjCheckNAdd(25); }
                  break;
               case 26:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(27, 28); }
                  break;
               case 27:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(27, 28); }
                  break;
               case 28:
                  if (curChar == 34 && kind > 49)
                     kind = 49;
                  break;
               case 31:
                  if ((0x100002600L & l) != 0L)
                     { jjCheckNAddTwoStates(31, 41); }
                  break;
               case 47:
                  if ((0x100002600L & l) != 0L)
                     { jjAddStates(9, 10); }
                  break;
               case 57:
                  if (curChar == 39)
                     { jjCheckNAddStates(0, 5); }
                  break;
               case 58:
                  if (curChar == 45)
                     { jjCheckNAddTwoStates(59, 60); }
                  break;
               case 59:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(59, 60); }
                  break;
               case 60:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 62:
                  if (curChar == 45)
                     { jjCheckNAddTwoStates(63, 64); }
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(63, 64); }
                  break;
               case 64:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 30:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 14:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  if (curChar == 81)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 5:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  if (curChar == 79)
                     { jjAddStates(11, 12); }
                  else if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 13:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 44:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  if (curChar == 74)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 10:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 12:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 43:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 11:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 66:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  break;
               case 42:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 45:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 55;
                  else if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 69:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  break;
               case 67:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  break;
               case 68:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  break;
               case 15:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 6:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 48)
                        kind = 48;
                     { jjCheckNAddTwoStates(24, 25); }
                  }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     { jjCheckNAddTwoStates(22, 21); }
                  }
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 1:
                  if (kind > 5)
                     kind = 5;
                  { jjAddStates(6, 8); }
                  break;
               case 8:
                  if (curChar == 70 && kind > 39)
                     kind = 39;
                  break;
               case 9:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 16:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 21:
                  if ((0x7fffffeL & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  { jjCheckNAddTwoStates(22, 21); }
                  break;
               case 23:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  { jjCheckNAddTwoStates(24, 25); }
                  break;
               case 25:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  { jjCheckNAddTwoStates(24, 25); }
                  break;
               case 27:
                  { jjAddStates(13, 14); }
                  break;
               case 29:
                  if (curChar == 79)
                     { jjAddStates(11, 12); }
                  break;
               case 32:
                  if (curChar == 82 && kind > 37)
                     kind = 37;
                  break;
               case 33:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 36:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 46:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 48:
                  if (curChar == 71 && kind > 41)
                     kind = 41;
                  break;
               case 49:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 51:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 52:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 55:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 59:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjAddStates(15, 16); }
                  break;
               case 61:
                  if ((0x10000000100L & l) != 0L && kind > 45)
                     kind = 45;
                  break;
               case 63:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjAddStates(17, 18); }
                  break;
               case 65:
                  if ((0x400000004L & l) != 0L && kind > 46)
                     kind = 46;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjAddStates(6, 8); }
                  break;
               case 27:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(13, 14); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 66 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   58, 59, 60, 62, 63, 64, 1, 2, 4, 47, 53, 45, 56, 27, 28, 59, 
   60, 63, 64, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, "\173", "\175", "\50", "\51", "\133", 
"\135", "\56", "\54", "\174", "\73", "\104\105\106\111\116\111\124\111\117\116\123", 
"\102\105\107\111\116", "\105\116\104", "\72\72\75", "\111\115\120\117\122\124\123", 
"\105\130\120\117\122\124\123", "\106\122\117\115", "\111\115\120\114\111\103\111\124", 
"\115\101\103\122\117", "\124\105\130\124\125\101\114\55\103\117\116\126\105\116\124\111\117\116", 
"\117\102\112\105\103\124\55\124\131\120\105", "\124\122\101\120\55\124\131\120\105", 
"\117\102\112\105\103\124\55\111\104\105\116\124\111\124\131", "\117\102\112\105\103\124\55\107\122\117\125\120", 
"\116\117\124\111\106\111\103\101\124\111\117\116\55\107\122\117\125\120", "\115\117\104\125\114\105\55\111\104\105\116\124\111\124\131", 
"\115\117\104\125\114\105\55\103\117\115\120\114\111\101\116\103\105", "\101\107\105\116\124\55\103\101\120\101\102\111\114\111\124\111\105\123", 
"\116\117\124\111\106\111\103\101\124\111\117\116\55\124\131\120\105", "\123\131\116\124\101\130", "\111\115\120\114\111\105\104", null, 
"\103\110\117\111\103\105", null, "\123\105\121\125\105\116\103\105", null, 
"\111\116\124\105\107\105\122", "\102\111\124\123", null, null, null, null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public Parser4MIBTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public Parser4MIBTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 66; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x3ffffffffffc1L, 
};
static final long[] jjtoSkip = {
   0x3eL, 
};
static final long[] jjtoSpecial = {
   0x20L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[66];
    private final int[] jjstateSet = new int[2 * 66];

    
    protected char curChar;
}
