/* Generated By:JavaCC: Do not edit this line. Parser4MIBConstants.java */
package com.hellonms.platforms.emp_orange.share.parser.snmp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Parser4MIBConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int L_BRACE = 6;
  /** RegularExpression Id. */
  int R_BRACE = 7;
  /** RegularExpression Id. */
  int L_PAREN = 8;
  /** RegularExpression Id. */
  int R_PAREN = 9;
  /** RegularExpression Id. */
  int L_BRACKET = 10;
  /** RegularExpression Id. */
  int R_BRACKET = 11;
  /** RegularExpression Id. */
  int DOT = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int BAR = 14;
  /** RegularExpression Id. */
  int SEMI_COLON = 15;
  /** RegularExpression Id. */
  int DEFINITIONS = 16;
  /** RegularExpression Id. */
  int BEGIN = 17;
  /** RegularExpression Id. */
  int END = 18;
  /** RegularExpression Id. */
  int DEFINE = 19;
  /** RegularExpression Id. */
  int IMPORTS = 20;
  /** RegularExpression Id. */
  int EXPORTS = 21;
  /** RegularExpression Id. */
  int FROM = 22;
  /** RegularExpression Id. */
  int IMPLICIT = 23;
  /** RegularExpression Id. */
  int MACRO = 24;
  /** RegularExpression Id. */
  int TEXTUAL_CONVENTION = 25;
  /** RegularExpression Id. */
  int OBJECT_TYPE = 26;
  /** RegularExpression Id. */
  int TRAP_TYPE = 27;
  /** RegularExpression Id. */
  int OBJECT_IDENTITY = 28;
  /** RegularExpression Id. */
  int OBJECT_GROUP = 29;
  /** RegularExpression Id. */
  int NOTIFICATION_GROUP = 30;
  /** RegularExpression Id. */
  int MODULE_IDENTITY = 31;
  /** RegularExpression Id. */
  int MODULE_COMPLIANCE = 32;
  /** RegularExpression Id. */
  int AGENT_CAPABILITIES = 33;
  /** RegularExpression Id. */
  int NOTIFICATION_TYPE = 34;
  /** RegularExpression Id. */
  int SYNTAX = 35;
  /** RegularExpression Id. */
  int IMPLIED = 36;
  /** RegularExpression Id. */
  int OBJECT_IDENTIFIER = 37;
  /** RegularExpression Id. */
  int CHOICE = 38;
  /** RegularExpression Id. */
  int SEQUENCE_OF = 39;
  /** RegularExpression Id. */
  int SEQUENCE = 40;
  /** RegularExpression Id. */
  int OCTET_STRING = 41;
  /** RegularExpression Id. */
  int INTEGER = 42;
  /** RegularExpression Id. */
  int BITS = 43;
  /** RegularExpression Id. */
  int NUMBER = 44;
  /** RegularExpression Id. */
  int NUM_16 = 45;
  /** RegularExpression Id. */
  int NUM_2 = 46;
  /** RegularExpression Id. */
  int USTRING = 47;
  /** RegularExpression Id. */
  int WSTRING = 48;
  /** RegularExpression Id. */
  int CSTRING = 49;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\",\"",
    "\"|\"",
    "\";\"",
    "\"DEFINITIONS\"",
    "\"BEGIN\"",
    "\"END\"",
    "\"::=\"",
    "\"IMPORTS\"",
    "\"EXPORTS\"",
    "\"FROM\"",
    "\"IMPLICIT\"",
    "\"MACRO\"",
    "\"TEXTUAL-CONVENTION\"",
    "\"OBJECT-TYPE\"",
    "\"TRAP-TYPE\"",
    "\"OBJECT-IDENTITY\"",
    "\"OBJECT-GROUP\"",
    "\"NOTIFICATION-GROUP\"",
    "\"MODULE-IDENTITY\"",
    "\"MODULE-COMPLIANCE\"",
    "\"AGENT-CAPABILITIES\"",
    "\"NOTIFICATION-TYPE\"",
    "\"SYNTAX\"",
    "\"IMPLIED\"",
    "<OBJECT_IDENTIFIER>",
    "\"CHOICE\"",
    "<SEQUENCE_OF>",
    "\"SEQUENCE\"",
    "<OCTET_STRING>",
    "\"INTEGER\"",
    "\"BITS\"",
    "<NUMBER>",
    "<NUM_16>",
    "<NUM_2>",
    "<USTRING>",
    "<WSTRING>",
    "<CSTRING>",
  };

}
