/*
 * TRUNCATE
 */
ALTER SEQUENCE EMP_UPDATE_SEQ_FAULT RESTART WITH 1;
SELECT NEXTVAL('EMP_UPDATE_SEQ_FAULT');
ALTER SEQUENCE EMP_UPDATE_SEQ_NETWORK RESTART WITH 1;
SELECT NEXTVAL('EMP_UPDATE_SEQ_NETWORK');

TRUNCATE TABLE EMP_OPERATION_LOG RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_USER_SESSION RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_USER_MANAGE_NE_GROUP RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_USER RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_USER_GROUP_AUTHORITY RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_USER_GROUP RESTART IDENTITY CASCADE;

TRUNCATE TABLE EMP_ALARM_STATISTICS_MONTH RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_ALARM_STATISTICS_DAY RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_ALARM_STATISTICS_HOUR RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_ALARM_ACTIVE RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_ALARM RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_EVENT RESTART IDENTITY CASCADE;
ALTER SEQUENCE EMP_EVENT_ID_SEQ RESTART WITH 1;

TRUNCATE TABLE EMP_NE_STATISTICS_MONTH RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_NE_STATISTICS_DAY RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_NE_STATISTICS_HOUR RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_NE_STATISTICS_MINUTE RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_NE_STATISTICS_SYNC RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_NE_THRESHOLD RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_NE_INFO_VALUE RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_NE_INFO_INDEX RESTART IDENTITY CASCADE;

TRUNCATE TABLE EMP_NETWORK_LINK RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_NE_SESSION_SNMP RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_NE_SESSION_ICMP RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_NE RESTART IDENTITY CASCADE;
TRUNCATE TABLE EMP_NE_GROUP RESTART IDENTITY CASCADE;

TRUNCATE TABLE EMP_PREFERENCE RESTART IDENTITY CASCADE;




/*
 * ENVIRONMENT : PREFERENCE
 */
INSERT INTO EMP_PREFERENCE VALUES (CAST(x'10000001' AS int), '0.0.3', 'EMP', CURRENT_TIMESTAMP, 'EMP', CURRENT_TIMESTAMP); -- PREFERENCE_ONION_ENVIRONMENT_VERSION
INSERT INTO EMP_PREFERENCE VALUES (CAST(x'10000002' AS int), '127.0.0.1', 'EMP', CURRENT_TIMESTAMP, 'EMP', CURRENT_TIMESTAMP); -- PREFERENCE_ONION_ENVIRONMENT_SERVER_IP
INSERT INTO EMP_PREFERENCE VALUES (CAST(x'10001001' AS int), 'false', 'EMP', CURRENT_TIMESTAMP, 'EMP', CURRENT_TIMESTAMP); -- PREFERENCE_ONION_ENVIRONMENT_DATABASE_BACKUP_ADMIN_STATE
INSERT INTO EMP_PREFERENCE VALUES (CAST(x'10001002' AS int), '24', 'EMP', CURRENT_TIMESTAMP, 'EMP', CURRENT_TIMESTAMP); -- PREFERENCE_ONION_ENVIRONMENT_DATABASE_BACKUP_PERIOD
INSERT INTO EMP_PREFERENCE VALUES (CAST(x'10001003' AS int), '4', 'EMP', CURRENT_TIMESTAMP, 'EMP', CURRENT_TIMESTAMP); -- PREFERENCE_ONION_ENVIRONMENT_DATABASE_BACKUP_OFFSET
INSERT INTO EMP_PREFERENCE VALUES (CAST(x'10001004' AS int), '/emp_orange/db_backup', 'EMP', CURRENT_TIMESTAMP, 'EMP', CURRENT_TIMESTAMP); -- PREFERENCE_ONION_ENVIRONMENT_DATABASE_BACKUP_DIRECTORY
INSERT INTO EMP_PREFERENCE VALUES (CAST(x'10002001' AS int), '', 'EMP', CURRENT_TIMESTAMP, 'EMP', CURRENT_TIMESTAMP); -- PREFERENCE_ORANGE_NETWORK_NEDETAIL_DISPLAYORDER


/*
 * NETWORK : NE_GROUP
 */
INSERT INTO EMP_NE_GROUP (delete_state, left_bound, right_bound, parent_ne_group_id, ne_group_name, access, description, ne_group_icon, ne_group_map_bg_color, ne_group_map_bg_image, ne_group_map_location_x, ne_group_map_location_y, admin_state, creator, create_time, updater, update_time) VALUES (false, 1, 2, 1, 'NETWORK', 1, '', '/data/image/node_icon/NETWORK.png', CAST(x'FFFFFF' AS int), '', 0, 0, true, 'EMP', CURRENT_TIMESTAMP, 'EMP', CURRENT_TIMESTAMP);


/*
 * NETWORK : NE
 */
INSERT INTO EMP_NE (delete_state, ne_group_id, ne_code, ne_name, access, description, ne_icon, ne_map_location_x, ne_map_location_y, monitoring_timestamp, admin_state, meta_data, creator, create_time, updater, update_time) VALUES (false, 1, CAST(x'0900' AS int), 'NMS', 1, '', '/data/image/node_icon/NMS.png', 0, 0, CURRENT_TIMESTAMP, true, null, 'EMP', CURRENT_TIMESTAMP, 'EMP', CURRENT_TIMESTAMP);


/*
 * SECURITY : USER_GROUP
*/
INSERT INTO EMP_USER_GROUP (delete_state, user_group_account, access, description, admin_state, creator, create_time, updater, update_time ) VALUES (false, 'admin', 1, '', true, 'EMP', CURRENT_TIMESTAMP, 'EMP', CURRENT_TIMESTAMP);
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002111' AS int), true); -- OPERATION_ORANGE_NETWORK_NEGROUP_CREATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002113' AS int), true); -- OPERATION_ORANGE_NETWORK_NEGROUP_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002114' AS int), true); -- OPERATION_ORANGE_NETWORK_NEGROUP_UPDATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002115' AS int), true); -- OPERATION_ORANGE_NETWORK_NEGROUP_DELETE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002121' AS int), true); -- OPERATION_ORANGE_NETWORK_NE_CREATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002123' AS int), true); -- OPERATION_ORANGE_NETWORK_NE_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002124' AS int), true); -- OPERATION_ORANGE_NETWORK_NE_UPDATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002125' AS int), true); -- OPERATION_ORANGE_NETWORK_NE_DELETE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002911' AS int), true); -- ORANGE_SECURITY_USERSESSION_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002913' AS int), true); -- OPERATION_ORANGE_SECURITY_USERSESSION_LOGIN
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002914' AS int), true); -- OPERATION_ORANGE_SECURITY_USERSESSION_LOGOUT
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002915' AS int), false); -- OPERATION_ORANGE_SECURITY_USERSESSION_TERMINATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002921' AS int), false); -- ORANGE_SECURITY_USERGROUP_CREATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002923' AS int), true); -- ORANGE_SECURITY_USERGROUP_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002924' AS int), false); -- ORANGE_SECURITY_USERGROUP_UPDATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002925' AS int), false); -- ORANGE_SECURITY_USERGROUP_DELETE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002931' AS int), true); -- ORANGE_SECURITY_USER_CREATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002933' AS int), true); -- ORANGE_SECURITY_USER_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002934' AS int), true); -- ORANGE_SECURITY_USER_UPDATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (1, CAST(x'00002935' AS int), true); -- ORANGE_SECURITY_USER_DELETE


INSERT INTO EMP_USER_GROUP (delete_state, user_group_account, access, description, admin_state, creator, create_time, updater, update_time ) VALUES (false, 'operator', 1, '', true, 'EMP', CURRENT_TIMESTAMP, 'EMP', CURRENT_TIMESTAMP);
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002111' AS int), true); -- OPERATION_ORANGE_NETWORK_NEGROUP_CREATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002113' AS int), true); -- OPERATION_ORANGE_NETWORK_NEGROUP_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002114' AS int), true); -- OPERATION_ORANGE_NETWORK_NEGROUP_UPDATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002115' AS int), true); -- OPERATION_ORANGE_NETWORK_NEGROUP_DELETE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002121' AS int), true); -- OPERATION_ORANGE_NETWORK_NE_CREATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002123' AS int), true); -- OPERATION_ORANGE_NETWORK_NE_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002124' AS int), true); -- OPERATION_ORANGE_NETWORK_NE_UPDATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002125' AS int), true); -- OPERATION_ORANGE_NETWORK_NE_DELETE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002911' AS int), true); -- ORANGE_SECURITY_USERSESSION_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002913' AS int), true); -- OPERATION_ORANGE_SECURITY_USERSESSION_LOGIN
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002914' AS int), true); -- OPERATION_ORANGE_SECURITY_USERSESSION_LOGOUT
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002915' AS int), false); -- OPERATION_ORANGE_SECURITY_USERSESSION_TERMINATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002921' AS int), false); -- ORANGE_SECURITY_USERGROUP_CREATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002923' AS int), true); -- ORANGE_SECURITY_USERGROUP_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002924' AS int), false); -- ORANGE_SECURITY_USERGROUP_UPDATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002925' AS int), false); -- ORANGE_SECURITY_USERGROUP_DELETE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002931' AS int), false); -- ORANGE_SECURITY_USER_CREATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002933' AS int), true); -- ORANGE_SECURITY_USER_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002934' AS int), false); -- ORANGE_SECURITY_USER_UPDATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (2, CAST(x'00002935' AS int), false); -- ORANGE_SECURITY_USER_DELETE


INSERT INTO EMP_USER_GROUP (delete_state, user_group_account, access, description, admin_state, creator, create_time, updater, update_time ) VALUES (false, 'monitor', 1, '', true, 'EMP', CURRENT_TIMESTAMP, 'EMP', CURRENT_TIMESTAMP);
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002111' AS int), false); -- OPERATION_ORANGE_NETWORK_NEGROUP_CREATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002113' AS int), true); -- OPERATION_ORANGE_NETWORK_NEGROUP_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002114' AS int), false); -- OPERATION_ORANGE_NETWORK_NEGROUP_UPDATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002115' AS int), false); -- OPERATION_ORANGE_NETWORK_NEGROUP_DELETE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002121' AS int), false); -- OPERATION_ORANGE_NETWORK_NE_CREATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002123' AS int), true); -- OPERATION_ORANGE_NETWORK_NE_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002124' AS int), false); -- OPERATION_ORANGE_NETWORK_NE_UPDATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002125' AS int), false); -- OPERATION_ORANGE_NETWORK_NE_DELETE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002911' AS int), true); -- ORANGE_SECURITY_USERSESSION_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002913' AS int), true); -- OPERATION_ORANGE_SECURITY_USERSESSION_LOGIN
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002914' AS int), true); -- OPERATION_ORANGE_SECURITY_USERSESSION_LOGOUT
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002915' AS int), false); -- OPERATION_ORANGE_SECURITY_USERSESSION_TERMINATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002921' AS int), false); -- ORANGE_SECURITY_USERGROUP_CREATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002923' AS int), true); -- ORANGE_SECURITY_USERGROUP_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002924' AS int), false); -- ORANGE_SECURITY_USERGROUP_UPDATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002925' AS int), false); -- ORANGE_SECURITY_USERGROUP_DELETE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002931' AS int), false); -- ORANGE_SECURITY_USER_CREATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002933' AS int), true); -- ORANGE_SECURITY_USER_QUERY
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002934' AS int), false); -- ORANGE_SECURITY_USER_UPDATE
INSERT INTO EMP_USER_GROUP_AUTHORITY VALUES (3, CAST(x'00002935' AS int), false); -- ORANGE_SECURITY_USER_DELETE


/*
 * SECURITY : USER
*/
INSERT INTO EMP_USER (delete_state, user_group_id, user_account, password, password_time, access, user_name, user_email, telephone, mobilephone, alarm_email_state, alarm_sms_state, description, admin_state, creator, create_time, updater, update_time) VALUES (false, 1, 'admin', MD5('admin'), CURRENT_TIMESTAMP, 2, 'admin', '', '', '', '', '', '', true, 'EMP', CURRENT_TIMESTAMP, 'EMP', CURRENT_TIMESTAMP);
INSERT INTO EMP_USER_MANAGE_NE_GROUP (user_id, ne_group_id) VALUES (1, 1);

